sudo: false
language: node_js
node_js:
  - '7.7'
cache:
  directories:
    - node_modules
    - .eslintcache
notifications:
  webhooks:
    urls:
      - 'https://www.travisbuddy.com/'
    on_success: never
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: never
