sudo: false
language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
    - .eslintcache
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: change
travisBuddy:
  insertMode: update
